export const siteStats = {
  projectsDelivered: 5,
  hackathonsWon: 4,
  teamMembers: 16,
  technologiesUsed: 35,
};

import { Project } from "@/types/project";

export const demoProjects: Project[] = [
  {
    id: "p1",
    title: "HostelHub – AI-Powered Hostel Security & Management System",
    slug: "hostelhub",
    summary: "Distributed college hostel security and management platform combining automated AI facial recognition with administrative modules.",
    type: "AI & Security System",
    status: "COMPLETED",
    year: "2026",
    problem: "Traditional hostels rely on manual security registers, tedious attendance, and lack real-time alerts for unauthorized access.",
    solution: "Automates perimeter security integrating deep learning (RetinaFace/ArcFace) to process camera feeds, logging attendance and flagging intruders via a decoupled 3-tier architecture.",
    features: [
      "AI Facial Recognition Attendance",
      "Intrusion Detection Alerts",
      "Role-Based Web Dashboard",
      "Grievance Module",
      "Food Feedback System"
    ],
    technologyStack: ["Python", "Flask", "SQLite", "OpenCV", "RetinaFace", "ArcFace", "HTML5", "CSS3", "JavaScript"],
    coverImage: "",
    screenshots: [],
    demoUrl: "",
    repositoryUrl: "https://github.com/shv2312/HostelHub",
    teamMembers: ["Parthiban V", "Shri Hari Vishnu S", "Sanjay V"],
    outcome: "Achieved 100% automated security auditing processing 2,500+ frames seamlessly with a zero-trust decoupled architecture.",
    clientVisibility: "PUBLIC",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "p2",
    title: "LLM Hallucination & Response Quality Evaluator",
    slug: "llm-evaluator",
    summary: "Automated evaluation system to detect, measure, and mitigate hallucinations in Large Language Models.",
    type: "AI Reliability Framework",
    status: "OPEN SOURCE",
    year: "2026",
    problem: "LLMs frequently generate plausible but factually incorrect information, and manual auditing is unscalable in production.",
    solution: "A modular programmatic pipeline that evaluates LLM outputs against source reference documents using automated metrics and heuristic checks.",
    features: [
      "Faithfulness & Context Recall Scoring",
      "Automated Factuality Checks",
      "Configurable Evaluation Thresholds",
      "Structured Diagnostic Traces"
    ],
    technologyStack: ["Python", "FastAPI", "LangChain", "LlamaIndex", "NumPy", "Pandas"],
    coverImage: "",
    screenshots: [],
    demoUrl: "",
    repositoryUrl: "",
    teamMembers: ["Parthiban V", "Sanjay S", "Shri Hari Vishnu S"],
    outcome: "Successfully flags factual drift and contradictions in real-time.",
    clientVisibility: "PUBLIC",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "p3",
    title: "TrueVault — Decentralized Digital Identity & Asset Verification",
    slug: "truevault",
    summary: "Blockchain-based digital identity and asset verification platform for secure, tamper-resistant ownership.",
    type: "Web3 / Blockchain Platform",
    status: "COMPLETED",
    year: "2026",
    problem: "Centralized databases are single points of failure, ownership records can be manipulated, and transferring secure access requires manual processes.",
    solution: "Combines cryptographic identity, ERC-721 ownership records, RBAC, and AES-256-GCM encrypted off-chain storage to secure digital assets.",
    features: [
      "Cryptographic Identity",
      "Blockchain Ownership",
      "Role-Based Access Control",
      "Encrypted Storage",
      "SHA-256 Integrity Verification"
    ],
    technologyStack: ["React", "TypeScript", "Vite", "Node.js", "Express", "PostgreSQL", "Prisma", "Solidity", "Hardhat"],
    coverImage: "",
    screenshots: [],
    demoUrl: "",
    repositoryUrl: "https://github.com/shv2312/YHACK26_YS527_Alchemist.git",
    teamMembers: ["Shri Hari Vishnu S", "Sanjay V", "Parthiban V"],
    outcome: "Demonstrated a practical architecture combining Web3 proofs with conventional full-stack encrypted storage.",
    clientVisibility: "PUBLIC",
    publishedAt: new Date().toISOString(),
  },
  {
    id: "p4",
    title: "Academic Background Verification Portal (SIET BGV)",
    slug: "siet-bgv",
    summary: "Institutional web platform for corporate employers to verify educational credentials and degree authenticity.",
    type: "Institutional Web Portal",
    status: "COMPLETED",
    year: "2026",
    problem: "Manual credential verification is slow, paper certificates risk forgery, and admin staff face high operational overhead.",
    solution: "A digital portal with a strict pipeline utilizing secure SMTP OTP authentication and automated algorithmic matching against institutional databases.",
    features: [
      "HR Email Verification (OTP)",
      "High-Performance Verification Engine",
      "Asynchronous Email Dispatch",
      "Public Status Tracking",
      "Admin Dashboard"
    ],
    technologyStack: ["React", "TypeScript", "Tailwind CSS", "FastAPI", "PostgreSQL", "SQLAlchemy", "asyncpg"],
    coverImage: "",
    screenshots: [],
    demoUrl: "",
    repositoryUrl: "https://github.com/shv2312/Certificate-Verification",
    teamMembers: ["Shri Hari Vishnu S", "Parthiban V", "Sanjay V"],
    outcome: "Eliminated verification turnaround time from days to near real-time with complete audit reliability.",
    clientVisibility: "PUBLIC",
    publishedAt: new Date().toISOString(),
  }
];

import { Hackathon } from "@/types/hackathon";

export const demoHackathons: Hackathon[] = [
  {
    id: "h1",
    slug: "hacksprint-26",
    name: "HACKSPRINT '26",
    organizer: "HACKSPRINT",
    date: "July 2026",
    year: "2026",
    location: "Offline",
    eventType: "GLOBAL",
    problem: "Traditional college hostels rely heavily on manual security registers, creating critical security and operational vulnerabilities.",
    solution: "HostelHub automates perimeter security and administrative operations by combining high-performance deep learning facial recognition with a centralized web dashboard.",
    architecture: "Decoupled 3-laptop architecture: Flask Backend/SQLite on Node 1, Frontend on Node 2, and dedicated AI Recognition microservice on Node 3.",
    technologies: ["Python", "Flask", "SQLite", "OpenCV", "RetinaFace", "ArcFace"],
    teamMembers: ["Parthiban V", "Shri Hari Vishnu S", "Sanjay V"],
    repositoryUrl: "https://github.com/shv2312/HostelHub",
    demoUrl: "",
    result: "WINNER",
    award: "1st Place - Best Solution",
    media: [],
    lessonsLearned: [
      "Decoupled architecture scalability: Keeping the AI processing isolated while routing through Flask ensured rock-solid system stability.",
      "Temporal Tracking Optimization: Implementing frame sequencing eliminated false positives from transient motion artifacts."
    ]
  },
  {
    id: "h2",
    slug: "ai-innovation-hackathon-2026",
    name: "AI Innovation Hackathon 2026",
    organizer: "AI Innovation",
    date: "September 2026",
    year: "2026",
    location: "Offline",
    eventType: "GLOBAL",
    problem: "Building an Interactive AI Teacher capable of delivering personalized and adaptive learning rather than simply generating static educational content.",
    solution: "Developed an AI-powered Interactive Teacher combining RAG, personalized lesson planning, adaptive teaching, and AI-generated teacher avatar videos.",
    architecture: "Content -> Document Processing -> RAG -> Lesson Planner -> Adaptive Engine -> Visuals/Voice -> Interactive Quiz -> Performance Analysis.",
    technologies: ["Python", "FastAPI", "React", "Vite", "Tailwind CSS", "Google Gemini", "RAG", "ChromaDB"],
    teamMembers: ["Parthiban V", "Shri Hari Vishnu S", "Sanjay V", "Sinduja SM"],
    repositoryUrl: "https://github.com/sanjayvisvanathan20012-source/AI-Innovation-Hack.git",
    result: "PARTICIPANT",
    award: "",
    media: [],
    lessonsLearned: [
      "Learned how to integrate Generative AI with a complete application workflow.",
      "Learned how to design an adaptive AI teaching loop based on learner interaction.",
      "Gained experience with AI-generated avatar/video pipelines and lip synchronization."
    ]
  },
  {
    id: "h3",
    slug: "yhack-26",
    name: "YHACK'26",
    organizer: "YHACK",
    date: "September 2026",
    year: "2026",
    location: "Offline",
    eventType: "GLOBAL",
    problem: "Developing a secure software solution around digital data/file security, controlled access, and identity-based authorization.",
    solution: "We developed a secure digital locker system that allows users to store and access sensitive files through controlled, role-based access.",
    architecture: "Frontend Web App connected to a REST API handling authentication, role-based access control, and encrypted file storage logic.",
    technologies: ["HTML", "CSS", "JavaScript", "React", "Python", "Flask"],
    teamMembers: ["Parthiban V", "Shri Hari Vishnu S", "Sanjay V", "Sinduja SM", "Sandhiya"],
    repositoryUrl: "https://github.com/shv2312/YHACK26_YS527_Alchemist.git",
    result: "PARTICIPANT",
    award: "",
    media: [],
    lessonsLearned: [
      "Designing a complete solution within a 24-hour hackathon requires prioritizing core functionality first.",
      "Security features must be considered from the beginning instead of being added as an afterthought.",
      "A working, demonstrable MVP is more valuable during a time-constrained hackathon than attempting too many unfinished features."
    ]
  }
];

export const demoMembers = [
  {
    id: "m1",
    name: "Parthiban V",
    tag: "Prince",
    role: "Founder & Lead Architect",
    image: "", 
    skills: ["Architecture", "Next.js", "AI/ML"],
    year: "Senior",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
  },
  {
    id: "m2",
    name: "Sindhuja S M",
    tag: "sindhu",
    role: "Developer",
    image: "", 
    skills: ["Java", "Python", "HTML", "CSS", "JavaScript", "React.js", "SQL"],
    year: "Member",
    github: "https://github.com/Sindhuja-wq",
    linkedin: "https://www.linkedin.com/in/sindhu-sm-bb56683b0",
  },
  {
    id: "m3",
    name: "Rithika",
    tag: "Aira",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "SQL", "Git", "AI/LLM"],
    year: "Member",
    github: "https://github.com/rithikarvrs",
    linkedin: "https://www.linkedin.com/in/rithika-r-b13b41377",
  },
  {
    id: "m4",
    name: "Shrivarsha M",
    tag: "Neko",
    role: "Developer",
    image: "", 
    skills: ["Java", "Python", "HTML", "CSS", "JavaScript", "SQL"],
    year: "Member",
    github: "https://github.com/shrivarsha62",
    linkedin: "https://www.linkedin.com/in/shrivarsham",
  },
  {
    id: "m5",
    name: "Shree Nithi Gobika S",
    tag: "Siri",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript"],
    year: "Member",
    github: "https://github.com/shreenithi3318-dotcom",
    linkedin: "https://www.linkedin.com/in/shree-nithi-ab1ba73ba",
  },
  {
    id: "m6",
    name: "Prijitha S",
    tag: "priji",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "Python"],
    year: "Member",
    github: "https://github.com/prijithasekar",
    linkedin: "https://www.linkedin.com/in/prijitha-s-01ab66400",
  },
  {
    id: "m7",
    name: "Shahana A.R",
    tag: "zaya",
    role: "Developer",
    image: "", 
    skills: ["Java", "JavaScript", "HTML", "CSS"],
    year: "Member",
    github: "https://github.com/arshahana68",
    linkedin: "https://www.linkedin.com/in/shahana-a-r-4076ab385",
  },
  {
    id: "m8",
    name: "Priya Dharshini A",
    tag: "Prini",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "Python", "C++", "SQL", "SQLite"],
    year: "Member",
    github: "https://github.com/priyadharshini699",
    linkedin: "https://www.linkedin.com/in/priyadharshini-a-7066683a8",
  },
  {
    id: "m9",
    name: "Sanjay V",
    tag: "Cheesyy",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "React", "JavaScript", "Bootstrap", "XML"],
    year: "Member",
    github: "https://github.com/sanjayvisvanathan20012-source",
    linkedin: "https://www.linkedin.com/in/sanjay-v-2207a3381",
  },
];

export const founderProfile = {
  name: "Parthiban V",
  tag: "Prince",
  role: "Founder & Lead Architect",
  vision: "To bridge the gap between academic theory and production-grade engineering by building a collective that treats every project like a real-world startup.",
  story: "DRACARYS was born from the realization that standard college portfolios weren't enough. We needed a crucible—an environment where passion for modern technology could be forged into real, impactful products.",
  philosophy: "Code is temporary, but the architecture of a team is permanent. True leadership in engineering means writing code that others can read, building systems that scale, and creating an environment where developers can transcend their limits.",
  skills: ["System Architecture", "Next.js ecosystem", "Cloud Infrastructure", "AI/ML Integration"],
  selectedWork: [
    { title: "HostelHub", role: "Lead Architect" },
    { title: "TrueVault", role: "Full-Stack Developer" }
  ],
  socials: {
    github: "https://github.com",
    linkedin: "https://linkedin.com"
  }
};

export const coreTechnologies = [
  "Next.js", "TypeScript", "React", "Tailwind CSS", "Framer Motion", "shadcn/ui",
  "SvelteKit", "Zod", "Vite", "Three.js", "Python", "FastAPI", "Node.js", "Flask",
  "Express.js", "Go (Golang)", "Rust", "tRPC", "GraphQL", "NestJS", "PostgreSQL",
  "Prisma", "SQLite", "Redis", "Supabase", "Drizzle ORM", "MongoDB", "SQLAlchemy",
  "LangChain", "LlamaIndex", "ChromaDB", "Pinecone", "OpenCV", "PyTorch",
  "Hugging Face", "Docker", "AWS", "Vercel", "GitHub Actions", "Cloudflare",
  "Kubernetes", "Solidity", "Hardhat", "Ethers.js"
];