export const siteStats = {
  projectsDelivered: 12,
  hackathonsWon: 8,
  teamMembers: 24,
  technologiesUsed: 15,
};

import { Project } from "@/types/project";

export const demoProjects: Project[] = [
  {
    id: "p1",
    title: "Nexys AI Framework",
    slug: "nexys-ai",
    summary: "A production-ready AI agent framework built for enterprise workflows.",
    type: "AI / Infrastructure",
    status: "DELIVERED",
    year: "2026",
    problem: "[DEMO] Enterprise teams struggle to orchestrate multiple LLM agents without hitting severe rate limits and context window degradation.",
    solution: "[DEMO] We built a distributed queuing system using Redis and FastAPI that acts as an intelligent proxy, routing tasks to specialized agents based on computational load.",
    features: ["Intelligent Routing", "Auto-scaling Workers", "Context Memory Management", "Enterprise Role-Based Access"],
    technologyStack: ["Next.js", "Python", "FastAPI", "Redis", "PostgreSQL"],
    coverImage: "",
    screenshots: [],
    demoUrl: "https://example.com",
    teamMembers: ["Parthiban V", "Sarah Chen"],
    outcome: "Reduced API latency by 35% and increased successful agent interactions for a top-tier B2B client.",
    clientVisibility: "ANONYMIZED",
    publishedAt: "2026-02-15",
  },
  {
    id: "p2",
    title: "Dracarys Orbit",
    slug: "dracarys-orbit",
    summary: "Internal member portal and project management system.",
    type: "Web Application",
    status: "INTERNAL",
    year: "2025",
    problem: "[DEMO] Tracking hackathon wins, client project assignments, and internal resource allocation was becoming impossible through standard spreadsheets.",
    solution: "[DEMO] A centralized monolithic portal that handles authentication, role-based dashboards, and automated GitHub repository provisioning.",
    features: ["OAuth Integration", "Automated Repo Creation", "Resource Timeline", "Member Skill Matrix"],
    technologyStack: ["React", "PostgreSQL", "Prisma", "Tailwind CSS"],
    coverImage: "",
    screenshots: [],
    repositoryUrl: "https://github.com",
    teamMembers: ["Parthiban V", "David Kim"],
    outcome: "Streamlined onboarding time from 3 days to 45 minutes for new members.",
    clientVisibility: "PUBLIC",
    publishedAt: "2025-11-20",
  },
  {
    id: "p3",
    title: "Vanguard Sec",
    slug: "vanguard-sec",
    summary: "Automated vulnerability scanner for smart contracts.",
    type: "Security / Web3",
    status: "OPEN SOURCE",
    year: "2025",
    problem: "[DEMO] Web3 developers lacked a fast, local-first tool for identifying common reentrancy and overflow vulnerabilities before deploying to testnets.",
    solution: "[DEMO] A Rust-based CLI scanner integrated with a Next.js visualization dashboard that analyzes ASTs of Solidity contracts in milliseconds.",
    features: ["AST Analysis", "Millisecond Scanning", "Visual Dashboard", "CI/CD Integration"],
    technologyStack: ["Rust", "TypeScript", "Next.js"],
    coverImage: "",
    screenshots: [],
    repositoryUrl: "https://github.com",
    teamMembers: ["Elena Rostova"],
    outcome: "Adopted by 40+ hackathon teams globally and awarded 'Best Security Tool'.",
    clientVisibility: "PUBLIC",
    publishedAt: "2025-08-10",
  },
];

import { Hackathon } from "@/types/hackathon";

export const demoHackathons: Hackathon[] = [
  {
    id: "h1",
    slug: "global-tech-innovators-2026",
    name: "Global Tech Innovators Hackathon",
    organizer: "TechGlobal Forum",
    date: "March 2026",
    year: "2026",
    location: "Virtual",
    eventType: "GLOBAL",
    problem: "[DEMO] Tracking global supply chains for small businesses was fragmented and relied on manual entry, leading to high error rates.",
    solution: "[DEMO] We built 'EcoTrack', an automated supply chain management system that aggregates data across APIs and uses AI to predict delays.",
    architecture: "[DEMO] A Next.js frontend communicating with a serverless Python backend, backed by PostgreSQL and hosted on Vercel/AWS.",
    technologies: ["Next.js", "Python", "AWS", "PostgreSQL"],
    teamMembers: ["Parthiban V", "Sarah Chen", "David Kim"],
    repositoryUrl: "https://github.com",
    demoUrl: "https://example.com",
    result: "WINNER",
    award: "1st Place - Best Enterprise Solution",
    media: [],
    lessonsLearned: [
      "[DEMO] Serverless cold starts must be managed carefully when integrating third-party logistics APIs.",
      "[DEMO] Asynchronous task queues are vital for real-time dashboards."
    ]
  },
  {
    id: "h2",
    slug: "web3-builders-summit-2025",
    name: "Web3 Builders Summit",
    organizer: "Ethereum Foundation",
    date: "November 2025",
    year: "2025",
    location: "New York, USA",
    eventType: "SPONSORED",
    problem: "[DEMO] Cross-chain yield farming was too complex for retail users, requiring multiple wallets and gas fees.",
    solution: "[DEMO] 'YieldDragon' – a smart contract protocol that automatically routes stablecoins to the highest yield across L2 networks.",
    architecture: "[DEMO] Solidity smart contracts deployed on Arbitrum, with a React/ethers.js frontend for easy interactions.",
    technologies: ["Solidity", "React", "TypeScript", "Ethers.js"],
    teamMembers: ["Parthiban V", "Elena Rostova"],
    repositoryUrl: "https://github.com",
    result: "SPECIAL_RECOGNITION",
    award: "Best DeFi Implementation",
    media: [],
    lessonsLearned: [
      "[DEMO] Smart contract security and thorough AST scanning is more important than speed.",
      "[DEMO] UX is the biggest barrier to Web3 adoption."
    ]
  },
];

export const demoMembers = [
  {
    id: "m1",
    name: "Parthiban V",
    tag: "Prince",
    role: "Founder & Lead Architect",
    image: "", 
    skills: ["Architecture", "Next.js", "AI/ML"],
    year: "Senior",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
  },
  {
    id: "m2",
    name: "Sindhuja S M",
    tag: "sindhu",
    role: "Developer",
    image: "", 
    skills: ["Java", "Python", "HTML", "CSS", "JavaScript", "React.js", "SQL"],
    year: "Member",
    github: "https://github.com/Sindhuja-wq",
    linkedin: "https://www.linkedin.com/in/sindhu-sm-bb56683b0",
  },
  {
    id: "m3",
    name: "Rithika",
    tag: "Aira",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "SQL", "Git", "AI/LLM"],
    year: "Member",
    github: "https://github.com/rithikarvrs",
    linkedin: "https://www.linkedin.com/in/rithika-r-b13b41377",
  },
  {
    id: "m4",
    name: "Shrivarsha M",
    tag: "Neko",
    role: "Developer",
    image: "", 
    skills: ["Java", "Python", "HTML", "CSS", "JavaScript", "SQL"],
    year: "Member",
    github: "https://github.com/shrivarsha62",
    linkedin: "https://www.linkedin.com/in/shrivarsham",
  },
  {
    id: "m5",
    name: "Shree Nithi Gobika S",
    tag: "Siri",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript"],
    year: "Member",
    github: "https://github.com/shreenithi3318-dotcom",
    linkedin: "https://www.linkedin.com/in/shree-nithi-ab1ba73ba",
  },
  {
    id: "m6",
    name: "Prijitha S",
    tag: "priji",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "Python"],
    year: "Member",
    github: "https://github.com/prijithasekar",
    linkedin: "https://www.linkedin.com/in/prijitha-s-01ab66400",
  },
  {
    id: "m7",
    name: "Shahana A.R",
    tag: "zaya",
    role: "Developer",
    image: "", 
    skills: ["Java", "JavaScript", "HTML", "CSS"],
    year: "Member",
    github: "https://github.com/arshahana68",
    linkedin: "https://www.linkedin.com/in/shahana-a-r-4076ab385",
  },
  {
    id: "m8",
    name: "Priya Dharshini A",
    tag: "Prini",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "JavaScript", "Java", "Python", "C++", "SQL", "SQLite"],
    year: "Member",
    github: "https://github.com/priyadharshini699",
    linkedin: "https://www.linkedin.com/in/priyadharshini-a-7066683a8",
  },
  {
    id: "m9",
    name: "Sanjay V",
    tag: "Cheesyy",
    role: "Developer",
    image: "", 
    skills: ["HTML", "CSS", "React", "JavaScript", "Bootstrap", "XML"],
    year: "Member",
    github: "https://github.com/sanjayvisvanathan20012-source",
    linkedin: "https://www.linkedin.com/in/sanjay-v-2207a3381",
  },
];

export const founderProfile = {
  name: "Parthiban V",
  tag: "Prince",
  role: "Founder & Lead Architect",
  vision: "To bridge the gap between academic theory and production-grade engineering by building a collective that treats every project like a real-world startup.",
  story: "DRACARYS was born from the realization that standard college portfolios weren't enough. We needed a crucible—an environment where passion for modern technology could be forged into real, impactful products.",
  philosophy: "Code is temporary, but the architecture of a team is permanent. True leadership in engineering means writing code that others can read, building systems that scale, and creating an environment where developers can transcend their limits.",
  skills: ["System Architecture", "Next.js ecosystem", "Cloud Infrastructure", "AI/ML Integration"],
  selectedWork: [
    { title: "Nexys AI Framework", role: "Lead Architect" },
    { title: "Dracarys Orbit System", role: "Full-Stack Developer" }
  ],
  socials: {
    github: "https://github.com",
    linkedin: "https://linkedin.com"
  }
};

import { Launcher } from "@/types/launcher";

export const demoLaunchers: Launcher[] = [
  {
    id: "l1",
    slug: "dracarys-nextjs-starter",
    title: "Dracarys Next.js Starter",
    version: "v2.4.1",
    description: "[DEMO] Our opinionated, production-ready Next.js boilerplate complete with Tailwind v4, shadcn/ui, Framer Motion, and pre-configured strict ESLint.",
    features: ["Pre-configured strict TypeScript", "Framer Motion included", "Dark Mode first", "Custom glassmorphism utilities"],
    category: "STARTER_KIT",
    license: "MIT",
    repositoryUrl: "https://github.com",
    releaseUrl: "https://example.com",
    maintainer: "Parthiban V",
    releaseDate: "2026-01-10",
    technologyStack: ["Next.js", "Tailwind CSS", "TypeScript"],
    coverImage: "",
  },
  {
    id: "l2",
    slug: "shadcn-extended",
    title: "Shadcn Extended",
    version: "v1.0.5",
    description: "[DEMO] A premium collection of highly customized UI components crafted for the Dragon design system, built on top of shadcn/ui.",
    features: ["Liquid Glass Components", "Glow Cursors", "Particle Atmospheres", "Animated Data Grids"],
    category: "TOOL",
    license: "MIT",
    repositoryUrl: "https://github.com",
    maintainer: "Alex Rivera",
    releaseDate: "2025-10-05",
    technologyStack: ["React", "Framer Motion", "CSS"],
    coverImage: "",
  },
  {
    id: "l3",
    slug: "orbit-cli",
    title: "Orbit CLI",
    version: "v0.9.0-beta",
    description: "[DEMO] Command-line utility to instantly provision GitHub repositories and setup standard DRACARYS CI/CD pipelines.",
    features: ["1-click Repo Generation", "Auto-protect main branch", "Vercel integration", "Automated secret injection"],
    category: "UTILITY",
    license: "APACHE_2.0",
    repositoryUrl: "https://github.com",
    maintainer: "David Kim",
    releaseDate: "2025-12-12",
    technologyStack: ["Go", "Bash", "GitHub Actions"],
    coverImage: "",
  },
];

export const coreTechnologies = [
  "Next.js", "TypeScript", "React", "Tailwind CSS", 
  "PostgreSQL", "Prisma", "Python", "FastAPI",
  "Docker", "AWS", "Framer Motion", "Zod"
];
